const scenarios={
 baseline:{label:'Routine processing',state:'On track',className:'',expected:'Processing completes inside the agreed operating window.',observed:'Stage events, lineage evidence, and SLA telemetry agree.',anomaly:'No material divergence detected.',owner:'Operations lead owns flow; automation advances eligible work.',client:'Processing on track - next status at validation.',decision:'Continue automated orchestration.'},
 collection:{label:'Collection lag',state:'Attention',className:'warning',expected:'Custodian collection complete before downstream processing starts.',observed:'One source remains incomplete while dependent work is queued.',anomaly:'AI flags a completeness and timing divergence before handoff.',owner:'Collections lead validates source, impact, and revised handoff.',client:'Collection validation in progress - downstream work protected.',decision:'Hold dependent automation; resolve source evidence.'},
 variance:{label:'Processing variance',state:'Human review',className:'hold',expected:'Processed volume reconciles to intake and exception thresholds.',observed:'Volume delta exceeds the approved tolerance for this matter.',anomaly:'Anomaly model surfaces an unexplained reconciliation gap.',owner:'Processing lead and quality owner inspect lineage and logs.',client:'Quality review active - release remains controlled.',decision:'Human authority required before release.'},
 review:{label:'Review volume shift',state:'Re-plan',className:'warning',expected:'Review throughput supports the committed production window.',observed:'New responsive volume changes workload and delivery forecast.',anomaly:'Forecast detects SLA risk before the deadline is threatened.',owner:'Client Services aligns staffing, scope, and client choice.',client:'Forecast updated - options ready for client decision.',decision:'Present tradeoffs; re-baseline with client approval.'},
 sla:{label:'SLA risk',state:'Escalate',className:'hold',expected:'Critical stage completes within the committed SLA.',observed:'Dependency delay compresses remaining recovery time.',anomaly:'Leading indicators predict missed SLA without intervention.',owner:'Matter owner convenes Ops, CS, and Engineering response.',client:'SLA risk identified - mitigation owner assigned.',decision:'Escalate with evidence, options, and next update time.'}
};
function applyScenario(key){const s=scenarios[key];document.querySelectorAll('[data-scenario]').forEach(b=>b.setAttribute('aria-selected',String(b.dataset.scenario===key)));const map={state:'statePill',expected:'expected',observed:'observed',anomaly:'anomaly',owner:'owner',client:'clientState',decision:'decision'};for(const [k,id] of Object.entries(map)){const el=document.getElementById(id);if(el)el.textContent=s[k]||s.state}const pill=document.getElementById('statePill');if(pill)pill.className='state-pill '+s.className;const sheet=document.querySelector('.contract-sheet');if(sheet){sheet.classList.remove('assembled');void sheet.offsetWidth;sheet.classList.add('assembled');const clauses=[...sheet.querySelectorAll('.clause')];clauses.forEach(c=>c.dataset.state='');if(key==='collection')clauses[0].dataset.state='warning';if(key==='variance')clauses[2].dataset.state='hold';if(key==='review')clauses[3].dataset.state='warning';if(key==='sla')clauses[4].dataset.state='hold';const ms=document.getElementById('matterStatus');if(ms){ms.textContent=s.state;ms.style.color=s.className==='hold'?'var(--danger)':s.className==='warning'?'#8a5700':'var(--success)'}const pc=document.getElementById('portalCopy');if(pc)pc.textContent=s.client}}
function resolveScenario(){const pill=document.getElementById('statePill');if(!pill)return;pill.textContent='Resolved';pill.className='state-pill';document.getElementById('observed').textContent='Human review confirmed the exception, corrective action, and evidence trail.';document.getElementById('anomaly').textContent='Detection event retained for evaluation, threshold tuning, and recurrence analysis.';document.getElementById('owner').textContent='Named owner closes the exception and approves the next automated step.';document.getElementById('clientState').textContent='Exception resolved - controlled work resumed.';document.getElementById('decision').textContent='Resume with complete decision evidence.';document.querySelectorAll('.clause').forEach(c=>{if(c.dataset.state)c.dataset.state='resolved'});const pc=document.getElementById('portalCopy');if(pc)pc.textContent='Exception resolved - controlled work resumed.'}
document.addEventListener('DOMContentLoaded',()=>{document.querySelectorAll('[data-scenario]').forEach(b=>b.addEventListener('click',()=>applyScenario(b.dataset.scenario)));document.getElementById('resolveBtn')?.addEventListener('click',resolveScenario);document.querySelector('.contract-sheet')?.classList.add('assembled');});
